### PR TITLE
Link development branches to issues and remove bugfix and feature wrappers over `branch`

### PR DESCRIPTION
**Pull request by willsawyerrrr**

### CODE REVIEW

**Comment by willsawyerrrr** [comment]
Branch names must be constructed such that they are prefixed with `bug/` or `feature/` so that labelling works.

**Comment by willsawyerrrr** [comment]
Closes #19.

**Comment by willsawyerrrr** [comment]
Consider that linking development branches to issues is [currently in public beta and subject to change](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue). It also works temperamentally.

**Comment by andre-at-situ** [comment]
Is there any way we can pick up on github issue labels? That way we get the best of both worlds.

**Comment by willsawyerrrr** [comment]
> Is there any way we can pick up on github issue labels? That way we get the best of both worlds.

For what purpose? Branch name prefixes?

**Comment by willsawyerrrr** [comment]
> > Is there any way we can pick up on github issue labels? That way we get the best of both worlds.
> 
> For what purpose? Branch name prefixes?

@andre-at-situ

**Comment by willsawyerrrr** [comment]
> Branch names must be constructed such that they are prefixed with `bug/` or `feature/` so that labelling works.

This has been implemented. It also handles branches which require the `chore/` prefix.

**Comment by willsawyerrrr** [comment]
> Branch names must be constructed such that they are prefixed with `bug/` or `feature/` so that labelling works.

This has been implemented. It also handles branches which require the `chore/` prefix.

> Is there any way we can pick up on github issue labels? That way we get the best of both worlds.

The implementation uses issue labels. I assume that's what you meant @andre-at-situ.

**Review by andre-at-situ — DISMISSED** [review]

**Review by andre-at-situ — APPROVED** [review]

**Pull request merged**
