### PR TITLE
Update Default Branches

### PR DESCRIPTION
**Pull request by willsawyerrrr**
- Deprecated `github`
- Deprecated `prod`
- Defaulted `feature-branch` base branch to repository's default branch
- Added default base branch to `create-pr`

### CODE REVIEW

**Comment by Sassiest01** [comment]
Instead of deprecating prod, can we change it's usage to be for merging feature branches that don't require review? That is what I have been using it for mostly. So it would be getting the branch name from the current directory, then defaulting to merge into main (or making use of the default branch). Potentially it could set automerge and wait for status checks (and show if a status check fails).

**Comment by willsawyerrrr** [comment]
`create-pr` provides this functionality.

**Comment by Sassiest01** [comment]
create-pr automatically requests for review even if it is not needed on certain repos, is this something that can be done conditionally?

**Comment by willsawyerrrr** [comment]
Why do you think this is desirable?

**Comment by Sassiest01** [comment]
Because otherwise we will be requested for review for every pull request regardless of if a review is actually required which isn't necessary.

**Comment by willsawyerrrr** [comment]
I've converted this discussion to an issue. We'll continue at #63.
Please review this PR so it can be merged first.

**Review by Sassiest01 — APPROVED** [review]

**Pull request merged**
